import { OrderType } from "@/src/components/orders/OrderCard";

export const mockOrders: OrderType[] = [
  {
    id: "#ORD-84920174",
    shopName: "Balaji Mart",
    statusKey: "PENDING",
    timestamp: "Today, 12:45 PM",
    price: "₹580",
    paymentStatus: "Paid",
    itemsCount: 3,
    mainItemName: "Fortune Sunflower Oil (1L)",
  },
  {
    id: "#ORD-84920175",
    shopName: "Fresh Veggies & Fruits",
    statusKey: "ACCEPTED",
    timestamp: "Today, 12:30 PM",
    price: "₹240",
    paymentStatus: "Paid",
    itemsCount: 5,
    mainItemName: "Farm Fresh Tomatoes (1kg)",
    eta: "30-40 mins",
    deliveryAddress: "Home • 89 Tilak Marg",
  },
  {
    id: "#ORD-84920176",
    shopName: "Kailash Sweets",
    statusKey: "PREPARING",
    timestamp: "Today, 12:15 PM",
    price: "₹450",
    paymentStatus: "Paid",
    itemsCount: 2,
    mainItemName: "Kaju Katli (500g)",
    eta: "25-30 mins",
    deliveryAddress: "Home • 89 Tilak Marg",
  },
  {
    id: "#ORD-84920177",
    shopName: "Gupta Groceries",
    statusKey: "ASSIGNED",
    timestamp: "Today, 11:45 AM",
    price: "₹1,200",
    paymentStatus: "Paid",
    itemsCount: 12,
    mainItemName: "Aashirvaad Atta (5kg)",
    eta: "15-20 mins",
    deliveryAddress: "Office • Tech Park Phase 1",
    deliveryCode: "8294",
    deliveryPartnerName: "Rahul Kumar",
  },
  {
    id: "#ORD-84920178",
    shopName: "Pharmacy Plus",
    statusKey: "OUT_FOR_DELIVERY",
    timestamp: "Today, 11:00 AM",
    price: "₹320",
    paymentStatus: "Paid",
    itemsCount: 4,
    mainItemName: "Crocin Advance (Strip of 15)",
    eta: "5-10 mins",
    deliveryAddress: "Home • 89 Tilak Marg",
    deliveryCode: "4582",
    deliveryPartnerName: "Amit Sharma",
  },
  {
    id: "#ORD-84920179",
    shopName: "Balaji Mart",
    statusKey: "DELIVERED",
    timestamp: "Yesterday, 08:30 PM",
    price: "₹890",
    paymentStatus: "Paid",
    itemsCount: 8,
    mainItemName: "Amul Butter (500g)",
    deliveryPartnerName: "Suresh Kumar",
  },
  {
    id: "#ORD-84920180",
    shopName: "Daily Needs Supermarket",
    statusKey: "REJECTED",
    timestamp: "Yesterday, 06:15 PM",
    price: "₹120",
    paymentStatus: "Refund Processing",
    itemsCount: 1,
    mainItemName: "Britannia NutriChoice Biscuits",
  },
  {
    id: "#ORD-84920181",
    shopName: "City Stationers",
    statusKey: "CANCELLED",
    timestamp: "Mon, 12 Jun, 02:30 PM",
    price: "₹450",
    paymentStatus: "Refunded",
    itemsCount: 4,
    mainItemName: "Classmate Notebooks (Set of 6)",
  },
  {
    id: "#ORD-84920182",
    shopName: "Pet Care Express",
    statusKey: "REFUNDED",
    timestamp: "Sun, 11 Jun, 10:00 AM",
    price: "₹1,450",
    paymentStatus: "Refunded",
    itemsCount: 2,
    mainItemName: "Pedigree Adult Dog Food (3kg)",
  },
  {
    id: "#ORD-84920183",
    shopName: "Spice Market",
    statusKey: "DELIVERED",
    timestamp: "Sat, 10 Jun, 07:45 PM",
    price: "₹340",
    paymentStatus: "Paid",
    itemsCount: 5,
    mainItemName: "MDH Garam Masala (100g)",
  },
  {
    id: "#ORD-84920184",
    shopName: "Fresh Veggies & Fruits",
    statusKey: "DELIVERED",
    timestamp: "Fri, 09 Jun, 09:15 AM",
    price: "₹560",
    paymentStatus: "Paid",
    itemsCount: 10,
    mainItemName: "Onions (2kg)",
  },
  {
    id: "#ORD-84920185",
    shopName: "Sharma Bakeries",
    statusKey: "READY_FOR_PICKUP",
    timestamp: "Today, 01:15 PM",
    price: "₹350",
    paymentStatus: "Paid",
    itemsCount: 2,
    mainItemName: "Pineapple Cake (500g)",
    deliveryMethod: "PICKUP",
    pickupAddress: "Shop 12, Main Market",
    deliveryCode: "1122",
  },
  {
    id: "#ORD-84920186",
    shopName: "Gupta Groceries",
    statusKey: "PICKED_UP",
    timestamp: "Yesterday, 04:30 PM",
    price: "₹820",
    paymentStatus: "Paid",
    itemsCount: 5,
    mainItemName: "Basmati Rice (5kg)",
    deliveryMethod: "PICKUP",
    pickupAddress: "Shop 4, South Avenue",
  }
];
