export const SELECT_ADDRESS = {
  current: {
    id: "a1f3d921",
    formattatedAddress: "221B MG Road, Indore, Madhya Pradesh",
    label: "home",
    receiverName: "Viraj Dayle",
    receiverPhone: "9876543210",
  },
  saved: [
    {
      id: "b7c2a551",
      formattatedAddress:
        "Orbit Mall, Vijay Nagar, Near aayush hospital , Indore",
      label: "work",
      receiverName: "Viraj Dayle",
      receiverPhone: "9876543210",
    },
    {
      id: "c9d4e882",
      formattatedAddress: "Tech Park Phase 2, Bhopal",
      label: "office",
      receiverName: "Aman Verma",
      receiverPhone: "9123456780",
    },
    {
      id: "d1f8a223",
      formattatedAddress: "Near Railway Station, Khandwa",
      label: "gym",
      receiverName: "Rohit Sharma",
      receiverPhone: "9988776655",
    },
    {
      id: "e4b3c912",
      formattatedAddress: "Rajwada Square, Indore",
      label: "shopping",
      receiverName: "Priya Patel",
      receiverPhone: "9012345678",
    },
    {
      id: "f8a7d102",
      formattatedAddress: "Saket Nagar, Bhopal",
      label: "friend",
      receiverName: "Neha Jain",
      receiverPhone: "9090909090",
    },
    {
      id: "g2c5e781",
      formattatedAddress: "Near Bus Stand, Ujjain",
      label: "travel",
      receiverName: "Karan Mehta",
      receiverPhone: "9345678123",
    },
    {
      id: "h9d1f443",
      formattatedAddress: "ITI Colony, Burhanpur",
      label: "parents",
      receiverName: "Suresh Dayle",
      receiverPhone: "9765432101",
    },
    {
      id: "i3a8b774",
      formattatedAddress: "Phoenix Mall, Indore",
      label: "mall",
      receiverName: "Anjali Singh",
      receiverPhone: "9871203456",
    },
    {
      id: "j6f4d990",
      formattatedAddress: "Civil Lines, Jabalpur",
      label: "hostel",
      receiverName: "Ravi Thakur",
      receiverPhone: "9811122233",
    },
    {
      id: "k1e7c663",
      formattatedAddress: "Near Airport Road, Indore",
      label: "pickup",
      receiverName: "Aditya Rao",
      receiverPhone: "9955667788",
    },
    {
      id: "l5b9a114",
      formattatedAddress: "Scheme No. 140, Indore",
      label: "apartment",
      receiverName: "Sneha Kapoor",
      receiverPhone: "9822334455",
    },
    {
      id: "m8c2d337",
      formattatedAddress: "New Market Area, Bhopal",
      label: "cafe",
      receiverName: "Yash Malviya",
      receiverPhone: "9700011122",
    },
  ],
};
