import type { Product } from "@/src/types/product";

export const SUPERMARKET_PRODUCTS: Product[] = [
  {
    id: 1,
    title: "Aashirvaad Premium Fresh Paneer (200ml)",
    price: 128,
    mrp: 208,
    unit: "200ml",
    inStock: false,
    image: require("@/src/assets/images/candy/dogfood.png"),
  },
  {
    id: 2,
    title: "HUL Pure Fresh Paneer (500g)",
    price: 372,
    mrp: 496,
    unit: "500g",
    inStock: true,
    image: require("@/src/assets/images/candy/salt.png"),
  },
  {
    id: 3,
    title: "Maggi Classic Toned Milk (250g)",
    price: 801,
    mrp: 911,
    unit: "250g",
    inStock: true,
    image: require("@/src/assets/images/candy/cupcake.png"),
  },
  {
    id: 4,
    title: "HUL Fresh Bathing Soap (2L)",
    price: 139,
    mrp: 229,
    unit: "2L",
    inStock: true,
    image: require("@/src/assets/images/candy/cake.png"),
  },
  {
    id: 5,
    title: "Fortune Super Mixed Fruit Juice (2L)",
    price: 473,
    mrp: 752,
    unit: "2L",
    inStock: false,
    image: require("@/src/assets/images/candy/pizza.png"),
  },
  {
    id: 6,
    title: "Maggi Premium Sparkling Cola (250g)",
    price: 692,
    mrp: 899,
    unit: "250g",
    inStock: true,
    image: require("@/src/assets/images/candy/sweetpotato.png"),
  },
  {
    id: 7,
    title: "HUL Organic Instant Coffee (100g)",
    price: 857,
    mrp: 903,
    unit: "100g",
    inStock: false,
    image: require("@/src/assets/images/candy/water.png"),
  },
  {
    id: 8,
    title: "Godrej Healthy Processed Cheese (10kg)",
    price: 175,
    mrp: 255,
    unit: "10kg",
    inStock: true,
    image: require("@/src/assets/images/candy/sugar.png"),
  },
  {
    id: 9,
    title: "Haldiram Premium Basmati Rice (1L)",
    price: 475,
    mrp: 651,
    unit: "1L",
    inStock: true,
    image: require("@/src/assets/images/candy/sugar.png"),
  },
  {
    id: 10,
    title: "Maggi Premium Greek Yogurt (3 Pieces)",
    price: 143,
    mrp: 158,
    unit: "3 Pieces",
    inStock: false,
    image: require("@/src/assets/images/candy/cream2.png"),
  },
  {
    id: 11,
    title: "Godrej Classic Liquid Detergent (2L)",
    price: 164,
    mrp: 257,
    unit: "2L",
    inStock: true,
    image: require("@/src/assets/images/candy/cupcake.png"),
  },
  {
    id: 12,
    title: "Tata Fresh Digestive Biscuits (1 Pack)",
    price: 118,
    mrp: 175,
    unit: "1 Pack",
    inStock: true,
    image: require("@/src/assets/images/candy/pudding.png"),
  },
  {
    id: 13,
    title: "Tata Premium Digestive Biscuits (1L)",
    price: 223,
    mrp: 379,
    unit: "1L",
    inStock: true,
    image: require("@/src/assets/images/candy/soap.png"),
  },
  {
    id: 14,
    title: "Haldiram Classic Anti-dandruff Shampoo (3 Pieces)",
    price: 133,
    mrp: 219,
    unit: "3 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/saucecan.png"),
  },
  {
    id: 15,
    title: "Aashirvaad Healthy Mixed Fruit Juice (6 Pieces)",
    price: 123,
    mrp: 176,
    unit: "6 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/sugar.png"),
  },
  {
    id: 16,
    title: "Tata Organic Raisins (100g)",
    price: 687,
    mrp: 917,
    unit: "100g",
    inStock: true,
    image: require("@/src/assets/images/candy/wine.png"),
  },
  {
    id: 17,
    title: "HUL Fresh Green Tea (5kg)",
    price: 425,
    mrp: 553,
    unit: "5kg",
    inStock: true,
    image: require("@/src/assets/images/candy/pineapple.png"),
  },
  {
    id: 18,
    title: "Britannia Healthy Fresh Paneer (3 Pieces)",
    price: 484,
    mrp: 808,
    unit: "3 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/cheese.png"),
  },
  {
    id: 19,
    title: "Amul Pure Sparkling Cola (1L)",
    price: 191,
    mrp: 239,
    unit: "1L",
    inStock: true,
    image: require("@/src/assets/images/candy/apple.png"),
  },
  {
    id: 20,
    title: "Godrej Healthy Toned Milk (10kg)",
    price: 228,
    mrp: 272,
    unit: "10kg",
    inStock: true,
    image: require("@/src/assets/images/candy/sushi.png"),
  },
  {
    id: 21,
    title: "Godrej Extra Instant Coffee (3 Pieces)",
    price: 196,
    mrp: 265,
    unit: "3 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/water.png"),
  },
  {
    id: 22,
    title: "HUL Classic Cashews (6 Pieces)",
    price: 587,
    mrp: 794,
    unit: "6 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/rice.png"),
  },
  {
    id: 23,
    title: "Nestle Fresh Processed Cheese (250g)",
    price: 876,
    mrp: 923,
    unit: "250g",
    inStock: true,
    image: require("@/src/assets/images/candy/salt.png"),
  },
  {
    id: 24,
    title: "Nestle Healthy Processed Cheese (5kg)",
    price: 347,
    mrp: 419,
    unit: "5kg",
    inStock: true,
    image: require("@/src/assets/images/candy/noodles2.png"),
  },
  {
    id: 25,
    title: "Britannia Organic Raisins (2L)",
    price: 565,
    mrp: 734,
    unit: "2L",
    inStock: true,
    image: require("@/src/assets/images/candy/sweetpotato.png"),
  },
  {
    id: 26,
    title: "Godrej Organic Pasteurized Butter (1 Pack)",
    price: 649,
    mrp: 747,
    unit: "1 Pack",
    inStock: true,
    image: require("@/src/assets/images/candy/coconut.png"),
  },
  {
    id: 27,
    title: "ITC Premium Toned Milk (10kg)",
    price: 292,
    mrp: 321,
    unit: "10kg",
    inStock: true,
    image: require("@/src/assets/images/candy/eggs.png"),
  },
  {
    id: 28,
    title: "Parle Super Instant Coffee (250g)",
    price: 804,
    mrp: 958,
    unit: "250g",
    inStock: true,
    image: require("@/src/assets/images/candy/biryani.png"),
  },
  {
    id: 29,
    title: "Haldiram Classic Cashews (5kg)",
    price: 477,
    mrp: 672,
    unit: "5kg",
    inStock: true,
    image: require("@/src/assets/images/candy/cheese.png"),
  },
  {
    id: 30,
    title: "Amul Deluxe Whole Wheat Atta (3 Pieces)",
    price: 209,
    mrp: 299,
    unit: "3 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/biscuit.png"),
  },
  {
    id: 31,
    title: "Maggi Deluxe Bathing Soap (3 Pieces)",
    price: 647,
    mrp: 771,
    unit: "3 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/softdrink.png"),
  },
  {
    id: 32,
    title: "Dabur Farm Fresh Greek Yogurt (500g)",
    price: 207,
    mrp: 226,
    unit: "500g",
    inStock: true,
    image: require("@/src/assets/images/candy/choclate.png"),
  },
  {
    id: 33,
    title: "Britannia Tasty Mixed Fruit Juice (100g)",
    price: 836,
    mrp: 973,
    unit: "100g",
    inStock: true,
    image: require("@/src/assets/images/candy/banana.png"),
  },
  {
    id: 34,
    title: "Britannia Original Toned Milk (2L)",
    price: 572,
    mrp: 923,
    unit: "2L",
    inStock: true,
    image: require("@/src/assets/images/candy/cupcake.png"),
  },
  {
    id: 35,
    title: "Aashirvaad Organic Raisins (6 Pieces)",
    price: 89,
    mrp: 146,
    unit: "6 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/bread.png"),
  },
  {
    id: 36,
    title: "Amul Original Anti-dandruff Shampoo (100g)",
    price: 343,
    mrp: 520,
    unit: "100g",
    inStock: true,
    image: require("@/src/assets/images/candy/coconut.png"),
  },
  {
    id: 37,
    title: "P&G Extra Potato Chips (6 Pieces)",
    price: 613,
    mrp: 758,
    unit: "6 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/biscuit.png"),
  },
  {
    id: 38,
    title: "ITC Deluxe Anti-dandruff Shampoo (2L)",
    price: 394,
    mrp: 705,
    unit: "2L",
    inStock: true,
    image: require("@/src/assets/images/candy/cake.png"),
  },
  {
    id: 39,
    title: "Amul Healthy Toned Milk (200ml)",
    price: 742,
    mrp: 990,
    unit: "200ml",
    inStock: true,
    image: require("@/src/assets/images/candy/sweetpotato.png"),
  },
  {
    id: 40,
    title: "Tata Farm Fresh Almonds (1kg)",
    price: 106,
    mrp: 132,
    unit: "1kg",
    inStock: true,
    image: require("@/src/assets/images/candy/pineapple.png"),
  },
  {
    id: 41,
    title: "Amul Farm Fresh Iodized Salt (200ml)",
    price: 670,
    mrp: 882,
    unit: "200ml",
    inStock: true,
    image: require("@/src/assets/images/candy/biscuit.png"),
  },
  {
    id: 42,
    title: "Amul Natural Pasteurized Butter (1kg)",
    price: 308,
    mrp: 400,
    unit: "1kg",
    inStock: true,
    image: require("@/src/assets/images/candy/pudding.png"),
  },
  {
    id: 43,
    title: "Godrej Premium Iodized Salt (500g)",
    price: 557,
    mrp: 634,
    unit: "500g",
    inStock: true,
    image: require("@/src/assets/images/candy/wine.png"),
  },
  {
    id: 44,
    title: "Tata Classic Almonds (2L)",
    price: 577,
    mrp: 902,
    unit: "2L",
    inStock: true,
    image: require("@/src/assets/images/candy/eggs.png"),
  },
  {
    id: 45,
    title: "Dabur Classic Toor Dal (200ml)",
    price: 195,
    mrp: 264,
    unit: "200ml",
    inStock: true,
    image: require("@/src/assets/images/candy/coconut.png"),
  },
  {
    id: 46,
    title: "Parle Classic Green Tea (1kg)",
    price: 301,
    mrp: 487,
    unit: "1kg",
    inStock: true,
    image: require("@/src/assets/images/candy/capsicum.png"),
  },
  {
    id: 47,
    title: "Amul Farm Fresh Liquid Detergent (6 Pieces)",
    price: 198,
    mrp: 326,
    unit: "6 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/eggs.png"),
  },
  {
    id: 48,
    title: "Amul Classic Refined Sugar (6 Pieces)",
    price: 821,
    mrp: 955,
    unit: "6 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/biscuit.png"),
  },
  {
    id: 49,
    title: "Maggi Premium Fresh Paneer (2L)",
    price: 372,
    mrp: 621,
    unit: "2L",
    inStock: true,
    image: require("@/src/assets/images/candy/pizza.png"),
  },
  {
    id: 50,
    title: "Nestle Farm Fresh Basmati Rice (5kg)",
    price: 275,
    mrp: 324,
    unit: "5kg",
    inStock: true,
    image: require("@/src/assets/images/candy/icecream.png"),
  },
  {
    id: 51,
    title: "Nestle Organic Iodized Salt (1 Pack)",
    price: 84,
    mrp: 114,
    unit: "1 Pack",
    inStock: true,
    image: require("@/src/assets/images/candy/seedbag.png"),
  },
  {
    id: 52,
    title: "Godrej Fresh Toned Milk (1 Pack)",
    price: 370,
    mrp: 514,
    unit: "1 Pack",
    inStock: true,
    image: require("@/src/assets/images/candy/biscuit.png"),
  },
  {
    id: 53,
    title: "P&G Extra Bhujia Namkeen (5kg)",
    price: 365,
    mrp: 446,
    unit: "5kg",
    inStock: true,
    image: require("@/src/assets/images/candy/frenchfries.png"),
  },
  {
    id: 54,
    title: "Maggi Organic Bhujia Namkeen (6 Pieces)",
    price: 355,
    mrp: 613,
    unit: "6 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/icecream.png"),
  },
  {
    id: 55,
    title: "Dabur Healthy Digestive Biscuits (2L)",
    price: 141,
    mrp: 194,
    unit: "2L",
    inStock: true,
    image: require("@/src/assets/images/candy/icecream2.png"),
  },
  {
    id: 56,
    title: "Patanjali Super Liquid Detergent (5kg)",
    price: 342,
    mrp: 463,
    unit: "5kg",
    inStock: true,
    image: require("@/src/assets/images/candy/cupcake.png"),
  },
  {
    id: 57,
    title: "Tata Original Iodized Salt (250g)",
    price: 613,
    mrp: 757,
    unit: "250g",
    inStock: true,
    image: require("@/src/assets/images/candy/softdrink.png"),
  },
  {
    id: 58,
    title: "Amul Pure Almonds (500g)",
    price: 283,
    mrp: 480,
    unit: "500g",
    inStock: true,
    image: require("@/src/assets/images/candy/eggs.png"),
  },
  {
    id: 59,
    title: "Amul Fresh Sparkling Cola (250g)",
    price: 520,
    mrp: 929,
    unit: "250g",
    inStock: true,
    image: require("@/src/assets/images/candy/avacado.png"),
  },
  {
    id: 60,
    title: "P&G Premium Greek Yogurt (100g)",
    price: 713,
    mrp: 939,
    unit: "100g",
    inStock: true,
    image: require("@/src/assets/images/candy/wine.png"),
  },
  {
    id: 61,
    title: "Nestle Classic Greek Yogurt (2L)",
    price: 292,
    mrp: 457,
    unit: "2L",
    inStock: true,
    image: require("@/src/assets/images/candy/apple.png"),
  },
  {
    id: 62,
    title: "Patanjali Pure Almonds (200ml)",
    price: 228,
    mrp: 380,
    unit: "200ml",
    inStock: true,
    image: require("@/src/assets/images/candy/cake.png"),
  },
  {
    id: 63,
    title: "Dabur Pure Greek Yogurt (5kg)",
    price: 331,
    mrp: 495,
    unit: "5kg",
    inStock: true,
    image: require("@/src/assets/images/candy/cheese.png"),
  },
  {
    id: 64,
    title: "Godrej Premium Mixed Fruit Juice (2L)",
    price: 373,
    mrp: 424,
    unit: "2L",
    inStock: true,
    image: require("@/src/assets/images/candy/soap.png"),
  },
  {
    id: 65,
    title: "Fortune Original Bhujia Namkeen (3 Pieces)",
    price: 796,
    mrp: 937,
    unit: "3 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/sushi.png"),
  },
  {
    id: 66,
    title: "Haldiram Farm Fresh Refined Sugar (5kg)",
    price: 566,
    mrp: 629,
    unit: "5kg",
    inStock: true,
    image: require("@/src/assets/images/candy/soda.png"),
  },
  {
    id: 67,
    title: "Britannia Premium Pasteurized Butter (1 Pack)",
    price: 398,
    mrp: 539,
    unit: "1 Pack",
    inStock: true,
    image: require("@/src/assets/images/candy/sushi.png"),
  },
  {
    id: 68,
    title: "P&G Extra Toor Dal (1kg)",
    price: 737,
    mrp: 838,
    unit: "1kg",
    inStock: true,
    image: require("@/src/assets/images/candy/seedbag.png"),
  },
  {
    id: 69,
    title: "P&G Deluxe Processed Cheese (6 Pieces)",
    price: 470,
    mrp: 841,
    unit: "6 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/seedbag.png"),
  },
  {
    id: 70,
    title: "Fortune Premium Toned Milk (5kg)",
    price: 502,
    mrp: 661,
    unit: "5kg",
    inStock: true,
    image: require("@/src/assets/images/candy/icecream.png"),
  },
  {
    id: 71,
    title: "P&G Deluxe Green Tea (3 Pieces)",
    price: 240,
    mrp: 321,
    unit: "3 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/soap.png"),
  },
  {
    id: 72,
    title: "Tata Organic Processed Cheese (2L)",
    price: 372,
    mrp: 665,
    unit: "2L",
    inStock: true,
    image: require("@/src/assets/images/candy/cupcake.png"),
  },
  {
    id: 73,
    title: "Amul Classic Fresh Paneer (200ml)",
    price: 834,
    mrp: 959,
    unit: "200ml",
    inStock: true,
    image: require("@/src/assets/images/candy/coconut.png"),
  },
  {
    id: 74,
    title: "Patanjali Tasty Processed Cheese (500g)",
    price: 518,
    mrp: 570,
    unit: "500g",
    inStock: true,
    image: require("@/src/assets/images/candy/water.png"),
  },
  {
    id: 75,
    title: "Dabur Pure Refined Sugar (2L)",
    price: 330,
    mrp: 348,
    unit: "2L",
    inStock: true,
    image: require("@/src/assets/images/candy/pineapple.png"),
  },
  {
    id: 76,
    title: "Godrej Tasty Sparkling Cola (6 Pieces)",
    price: 677,
    mrp: 779,
    unit: "6 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/avacado.png"),
  },
  {
    id: 77,
    title: "ITC Super Cashews (2L)",
    price: 429,
    mrp: 682,
    unit: "2L",
    inStock: true,
    image: require("@/src/assets/images/candy/noodles.png"),
  },
  {
    id: 78,
    title: "Nestle Extra Greek Yogurt (1kg)",
    price: 448,
    mrp: 640,
    unit: "1kg",
    inStock: true,
    image: require("@/src/assets/images/candy/dogfood.png"),
  },
  {
    id: 79,
    title: "Tata Natural Processed Cheese (1L)",
    price: 686,
    mrp: 847,
    unit: "1L",
    inStock: true,
    image: require("@/src/assets/images/candy/soap.png"),
  },
  {
    id: 80,
    title: "Nestle Deluxe Raisins (3 Pieces)",
    price: 366,
    mrp: 453,
    unit: "3 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/watermelon.png"),
  },
  {
    id: 81,
    title: "Amul Farm Fresh Bathing Soap (100g)",
    price: 290,
    mrp: 415,
    unit: "100g",
    inStock: true,
    image: require("@/src/assets/images/candy/frenchfries.png"),
  },
  {
    id: 82,
    title: "P&G Pure Toor Dal (1L)",
    price: 479,
    mrp: 695,
    unit: "1L",
    inStock: true,
    image: require("@/src/assets/images/candy/water.png"),
  },
  {
    id: 83,
    title: "Patanjali Original Bhujia Namkeen (6 Pieces)",
    price: 148,
    mrp: 188,
    unit: "6 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/dogfood.png"),
  },
  {
    id: 84,
    title: "Dabur Original Potato Chips (500g)",
    price: 326,
    mrp: 480,
    unit: "500g",
    inStock: true,
    image: require("@/src/assets/images/candy/saucecan.png"),
  },
  {
    id: 85,
    title: "P&G Healthy Bathing Soap (3 Pieces)",
    price: 582,
    mrp: 910,
    unit: "3 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/icecream2.png"),
  },
  {
    id: 86,
    title: "Tata Classic Refined Sugar (6 Pieces)",
    price: 329,
    mrp: 388,
    unit: "6 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/pudding.png"),
  },
  {
    id: 87,
    title: "Haldiram Natural Processed Cheese (100g)",
    price: 428,
    mrp: 461,
    unit: "100g",
    inStock: false,
    image: require("@/src/assets/images/candy/wine.png"),
  },
  {
    id: 88,
    title: "Aashirvaad Pure Cashews (10kg)",
    price: 211,
    mrp: 320,
    unit: "10kg",
    inStock: true,
    image: require("@/src/assets/images/candy/pudding.png"),
  },
  {
    id: 89,
    title: "Nestle Premium Greek Yogurt (6 Pieces)",
    price: 563,
    mrp: 696,
    unit: "6 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/softdrink.png"),
  },
  {
    id: 90,
    title: "Amul Farm Fresh Iodized Salt (1 Pack)",
    price: 489,
    mrp: 653,
    unit: "1 Pack",
    inStock: true,
    image: require("@/src/assets/images/candy/noodles2.png"),
  },
  {
    id: 91,
    title: "Parle Farm Fresh Fresh Paneer (500g)",
    price: 460,
    mrp: 742,
    unit: "500g",
    inStock: true,
    image: require("@/src/assets/images/candy/cream.png"),
  },
  {
    id: 92,
    title: "Britannia Organic Whole Wheat Atta (100g)",
    price: 535,
    mrp: 878,
    unit: "100g",
    inStock: true,
    image: require("@/src/assets/images/candy/apple.png"),
  },
  {
    id: 93,
    title: "Britannia Extra Bathing Soap (6 Pieces)",
    price: 207,
    mrp: 276,
    unit: "6 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/frenchfries.png"),
  },
  {
    id: 94,
    title: "Aashirvaad Natural Toned Milk (3 Pieces)",
    price: 232,
    mrp: 342,
    unit: "3 Pieces",
    inStock: true,
    image: require("@/src/assets/images/candy/saucecan.png"),
  },
  {
    id: 95,
    title: "Nestle Original Whole Wheat Atta (10kg)",
    price: 416,
    mrp: 570,
    unit: "10kg",
    inStock: true,
    image: require("@/src/assets/images/candy/soda.png"),
  },
  {
    id: 96,
    title: "Godrej Deluxe Almonds (1kg)",
    price: 574,
    mrp: 898,
    unit: "1kg",
    inStock: true,
    image: require("@/src/assets/images/candy/apple.png"),
  },
  {
    id: 97,
    title: "ITC Deluxe Toor Dal (5kg)",
    price: 479,
    mrp: 578,
    unit: "5kg",
    inStock: false,
    image: require("@/src/assets/images/candy/bread.png"),
  },
  {
    id: 98,
    title: "Britannia Farm Fresh Bhujia Namkeen (100g)",
    price: 883,
    mrp: 950,
    unit: "100g",
    inStock: true,
    image: require("@/src/assets/images/candy/bread.png"),
  },
  {
    id: 99,
    title: "Dabur Farm Fresh Instant Coffee (1L)",
    price: 630,
    mrp: 985,
    unit: "1L",
    inStock: true,
    image: require("@/src/assets/images/candy/banana.png"),
  },
  {
    id: 100,
    title: "HUL Deluxe Liquid Detergent (10kg)",
    price: 216,
    mrp: 252,
    unit: "10kg",
    inStock: true,
    image: require("@/src/assets/images/candy/noodles2.png"),
  },
];
